<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 */
class TransactionRepository extends EntityRepository
{
    public function getTransaction($transId, $customId) {
        $query = $this->getEntityManager()->createQuery(
          "
            SELECT tr.id AS transactionId, tr.amount, tr.date
            FROM AppBundle:Transaction tr
            WHERE tr.id = :transId
            AND tr.customId = :customId
          "
        );
        $query->setParameters(array('transId' => $transId, 'customId' => $customId));
        return $query->getResult()[0];
    }
}
